#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: da8b975
#
Name     : netcdf-fortran
Version  : 4.6.1
Release  : 1
URL      : https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.1.tar.gz
Source0  : https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.1.tar.gz
Summary  : NetCDF Client Library for Fortran
Group    : Development/Tools
License  : Apache-2.0
Requires: netcdf-fortran-bin = %{version}-%{release}
Requires: netcdf-fortran-lib = %{version}-%{release}
Requires: netcdf-fortran-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : gfortran
BuildRequires : graphviz
BuildRequires : netcdf-dev
BuildRequires : sed
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Unidata NetCDF Fortran Library
========================================
Overview
--------

%package bin
Summary: bin components for the netcdf-fortran package.
Group: Binaries
Requires: netcdf-fortran-license = %{version}-%{release}

%description bin
bin components for the netcdf-fortran package.


%package dev
Summary: dev components for the netcdf-fortran package.
Group: Development
Requires: netcdf-fortran-lib = %{version}-%{release}
Requires: netcdf-fortran-bin = %{version}-%{release}
Provides: netcdf-fortran-devel = %{version}-%{release}
Requires: netcdf-fortran = %{version}-%{release}

%description dev
dev components for the netcdf-fortran package.


%package lib
Summary: lib components for the netcdf-fortran package.
Group: Libraries
Requires: netcdf-fortran-license = %{version}-%{release}

%description lib
lib components for the netcdf-fortran package.


%package license
Summary: license components for the netcdf-fortran package.
Group: Default

%description license
license components for the netcdf-fortran package.


%prep
%setup -q -n netcdf-fortran-4.6.1
cd %{_builddir}/netcdf-fortran-4.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1708272202
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1708272202
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/netcdf-fortran
cp %{_builddir}/netcdf-fortran-%{version}/F03Interfaces_LICENSE %{buildroot}/usr/share/package-licenses/netcdf-fortran/12c65b72a7653fe87466ea28178b796f3e1fc9f9 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/libnetcdff.settings

%files bin
%defattr(-,root,root,-)
/usr/bin/nf-config

%files dev
%defattr(-,root,root,-)
/usr/include/netcdf.inc
/usr/include/netcdf.mod
/usr/include/netcdf4_f03.mod
/usr/include/netcdf4_nc_interfaces.mod
/usr/include/netcdf4_nf_interfaces.mod
/usr/include/netcdf_f03.mod
/usr/include/netcdf_fortv2_c_interfaces.mod
/usr/include/netcdf_nc_data.mod
/usr/include/netcdf_nc_interfaces.mod
/usr/include/netcdf_nf_data.mod
/usr/include/netcdf_nf_interfaces.mod
/usr/include/typesizes.mod
/usr/lib64/libnetcdff.so
/usr/lib64/pkgconfig/netcdf-fortran.pc
/usr/share/man/man3/netcdf_f77.3
/usr/share/man/man3/netcdf_fortran.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnetcdff.so.7
/usr/lib64/libnetcdff.so.7.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/netcdf-fortran/12c65b72a7653fe87466ea28178b796f3e1fc9f9
